MartynovStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
import debug_toolbar
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main_view),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('standartadmin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admins')),
    path('order/', include('ordersapp.urls', namespace='ordersapp')),
    path('auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    path('auth/verify/vk/oauth2/', include('social_django.urls', namespace='social')),

]
if settings.DEBUG:
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authapp/urls.py
from django.conf.urls import url
from django.urls import re_path, path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.conf.urls import url
from django.urls import path, re_path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),

    re_path('^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
    path('ajaxdelete/<int:pk>/', basketapp.basket_ajaxdelete, name='delete'),
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp' # название для приложения mainapp

# ссылки, которые относятся к mainapp

urlpatterns = [
    path('contact/', mainapp.contact_view, name='contact'),
    path('products/', mainapp.products_view, name='products'),
    path('index/', mainapp.main_view, name='index'),
    path('products/<int:pk>/', mainapp.products_view, name='category')
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User


# User.objects.all() - получить список всех пользователей

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)  # Category & Product должны быть связаны.
    # Картинка
    image = models.ImageField(upload_to='products', null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    # строковый тип
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(verbose_name='Описание')
    price = models.PositiveIntegerField(verbose_name='Цена')
    rating = models.PositiveIntegerField(verbose_name='Рейтинг', default=1)
    alt = models.CharField(max_length=255, verbose_name='Текст рисунка', default='Текст по умолчанию')
    # 1. 1 к 1 = в одной категории только 1 товар.
    # category = models.OneToOneField(Category)
    # 2. 1 к многим = в одной категории много товаров, но один товар только в одной категории
    category = models.ForeignKey(Category, on_delete=models.PROTECT)  # Выбираем эту, как наиболее простую.
    # Если понадобится - усложним 1 или 3й. Варианты при удалении:  CASCADE, SET_NULL, PROTECT Для автозаполнения
    # третьим аргументов в ForeignKey было null = True. после автозаполнения удалили и заново мигрировали модель 3.
    # Многое к многому = в одной категори много товаров, но и один товар может быть в нескольких категориях category
    # = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='products', null=True, blank=True)
    isTrendy = models.BooleanField(verbose_name='Товар сейчас в тренде?', default=False)
    isTopSlider = models.BooleanField(verbose_name='Товар должен быть в верхнем слайдере?', default=False)
    SlideNo = models.PositiveIntegerField(verbose_name='Номер слайда в карусели верхнего слайдера', null=True, blank=True)
    isHot = models.BooleanField(verbose_name='Горячее предложение?', default=False)
    imageHot = models.ImageField(verbose_name='Картинка должна быть 1366х800 px', upload_to='products_hot', null=True, blank=True)
    SlideHotNo = models.PositiveIntegerField(verbose_name='Номер слайда в карусели "HOT"', null=True, blank=True)
    isNew = models.BooleanField(verbose_name='Поместить товар в раздел "новое"?', default=False)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=1)
    isActive = models.BooleanField(verbose_name='Категория активна', default=True)

    @staticmethod #  статический метод - метод, к которому можно обращаться не через экземпляр класса, а через сам класс
    def get_items():
        return Product.objects.filter(isActive = True).order_by('category', 'name')

    def __str__(self):
        return self.name

    def discount(self):
        discount = 10
        result = round(self.price * (1 - (discount / 100)), 2)
        return result


class TrendyProduct(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(verbose_name='Описание')
    price = models.PositiveIntegerField(verbose_name='Цена')
    rating = models.PositiveIntegerField(verbose_name='Рейтинг', default=1)
    alt = models.CharField(max_length=255, verbose_name='Текст рисунка', default='Текст по умолчанию')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='Trendy_products', null=True, blank=True)

    def __str__(self):
        return self.name

    def discount(self):
        discount = 10
        result = round(self.price * (1 - (discount / 100)), 2)
        return result


class ContactCard(models.Model):
    name = models.CharField(max_length=32)
    city = models.CharField(max_length=255, verbose_name='Город', default='Город не указан')
    phone = models.CharField(max_length=255, verbose_name='Номер телефона',
                             default='Номер не указан')  # charfield для того, чтобы указывать номер с дефисами
    email = models.CharField(max_length=255, verbose_name='Электронная почта', default='Эдектронная почта не указана')
    address = models.CharField(max_length=455, verbose_name='Адрес', default='Адрес не указан')

    def __str__(self):
        return self.name

    # # число
    # n = models.IntegerField(max_length = 5, unique = True)
    # # float
    # n = models.FloatField()
    # # boolean
    # n = models.BooleanField()
    # # text
    # n = models.TextField()
    # # datetime
    # n = models.DateField()
    # n = models.DateTimeField()
    # # link
    # n = models.URLField()
    # # image
    # n = models.ImageField()
    # n = models.FileField()
    # # byte
    # n = models.BlobField()

mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import datetime
import json, os
from mainapp.models import Product, TrendyProduct, ContactCard, Category
from basketapp.models import Basket
from django.contrib.auth.decorators import login_required, user_passes_test
import random
from django.views.generic import ListView
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page

# Create your views here.
current_date_text = 'Current date and time is: '
current_date_text = current_date_text.upper()
current_datetime = datetime.datetime.now()

path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'static',
                                    'data.json'))  # вышли из mainapp и зашли в статику к файлу data.json
with open(path) as json_data:
    data = json.load(json_data)
    json_data.close()

    # ===============================LOW CACHE=================================


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = Category.objects.all
            cache.set(key, links_menu)
        return links_menu
    else:
        return Category.objects.all


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(Category, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(Category, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(isActive=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(isActive=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordere  d_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(isActive=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(isActive=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, isActive=True). \
                order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, isActive=True). \
            order_by('price')

        # ===============================LOW CACHE=================================


def main_view(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    products = Product.objects.all().select_related('category')
    trendy_products = TrendyProduct.objects.all().select_related('category')[:6]  # максимум 6 первых (чтобы не перегружать страницу)
    content = {
        'datetime': current_datetime,
        'date_text': current_date_text,
        'data': data,
        'products': products,
        'trendy': trendy_products,
        'basket': basket,
    }
    return render(request, 'index.html', content)


def contact_view(request):
    contact_cards = ContactCard.objects.all()
    return render(request, 'contact.html',
                  {'contact_card': contact_cards, 'datetime': current_datetime, 'date_text': current_date_text,
                   'data': data})


def get_hot_product():
    products = Product.objects.filter(isActive=True)[:6]  # ограничение для количества Trendy на странице (6)
    return products

def get_new_product():
    new_product = Product.objects.filter(isNew=True)[:6]
    return new_product



#@cache_page(3600)  # также замораживает Горячее предложение на 3600 сек
def products_view(request, pk=None, page=1):
    new_products = get_new_product()
    basket = []
    products = Product.objects.all().select_related('category')[:9]
    title = 'продукты'
    links_menu = get_links_menu()
    hot_product = random.sample(list(Product.objects.filter(isActive=True)), 1)[0]  # ТОТ самый рандомайзер
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if pk:
        if pk is None:
            products = Product.objects.all().order_by('price')
            category = {'name': 'All'}
        else:
            category = get_object_or_404(Category, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')[:6]

        paginator = Paginator(products, 2)
        try:
            # получение объектов нужной страницы
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            # последняя страница
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
            'datetime': current_datetime,
            'date_text': current_date_text,
            'data': data,  # JSON
            'new_products': new_products,
            'basket': basket,
            'hot_product': hot_product,
            'pk': pk,
        }
        return render(request, 'products.html', content)
    content = {
        'title': title,
        'links_menu': links_menu,
        'datetime': current_datetime,
        'date_text': current_date_text,
        'data': data,  # JSON
        'products': products,
        'new_products': new_products,
        'basket': basket,
        'hot_product': hot_product,
    }
    return render(request, 'products.html', content)

mainapp/templates/index.html
{% extends "base.html" %} {% load static %} {% block title %} Interior. Products. {% endblock %} {% block body %}

<body>
    <div class="container">
        <div class="slider1">
                <div class="wrapper">
                    <input type="radio" name="point" id="slide1" checked>
                    <input type="radio" name="point" id="slide2">
                    <input type="radio" name="point" id="slide3">
                    <input type="radio" name="point" id="slide4">
                    <input type="radio" name="point" id="slide5">
                    <div class="slider">
{% for product in products %}
{% if product.isTopSlider %}
                        <div class="slides slide{{product.SlideNo}}">
                            <div style="margin-left:100px" class="text">
                                <h3>TRENDING</h3>
                                <h2>{{product.name}}</h2>
                                <p style="">{{product.description}}</p>
                                <!-- ДА, тут не те ключи продуктов, видимо совпадение в базе идёт. Позже создам единую
                                 базу продуктов - все будут в All, и экземпляры оттуда буду в слайды затаскивать, думаю так-->
                                <a href="{% url 'basket:add' product.pk %}" class="buy">ORDER US <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
                            </div>
                            <img src="{{product.image.url}}" alt="Very good product" class="sliding_image">
                        </div>
{% endif %}
{% endfor %}
                    </div>
                    <div class="controls">
                        <label for="slide1"></label>
                        <label for="slide2"></label>
                        <label for="slide3"></label>
                        <label for="slide4"></label>
                        <label for="slide5"></label>
                    </div>
                </div>
{% endblock %}


{% block menu_and_logo_index %}
            <div class="padding_side_top">

{% include "inc/menu_top.html" %} {% endblock %} {% block index_slider %}
            </div>
            <!-- {{ data.posts.0.title }} - json пример вывода -->
        </div>
{% endblock %}

        <!-- КОНЕЦ СЛАЙДЕРА -->
{% block underslide_space %}
        <div class="underslide_space">
            <ul class="featured_new_menu">
                <li><a class="featured_menu_active" href="#">Featured</a></li>
                <li><a href="#">New</a></li>
            </ul>
            <a href="{% url 'main:index' %}" class="explore_all">EXPLORE ALL <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'Right_arrow_buy.png' %}" alt=""></a>
        </div>
{% endblock %} {% block featured_products %}
        <div class="product_images padding_side">
            <div class="product">
                <img src="{% static 'img/product-1.jpg' %}" alt="product-1">
                <div class="product-info">
                    <a class="round_button" href="#">&gt;</a>
                    <h3>Fishnet Chair</h3>
                    <p>Seat and back with upholstery made of&nbsp;cold cure foam</p>
                </div>
            </div>
            <div class="product">
                <img src="{% static 'img/product-2.jpg' %}" alt="product-2">
                <div class="product-info">
                    <a class="round_button" href="#">&gt;</a>
                    <h3>Fishnet Chair</h3>
                    <p>Seat and back with upholstery made of&nbsp;cold cure foam</p>
                </div>
            </div>
            <div class="product">
                <img src="{% static 'img/product-3.jpg' %}" alt="product-3">
                <div class="product-info">
                    <a class="round_button" href="#">&gt;</a>
                    <h3>Fishnet Chair</h3>
                    <p>Seat and back with upholstery made of&nbsp;cold cure foam</p>
                </div>
            </div>
            <div class="product">
                <img src="{% static 'img/product-4.jpg' %}" alt="product-4">
                <div class="product-info">
                    <a class="round_button" href="#">&gt;</a>
                    <h3>Fishnet Chair</h3>
                    <p>Seat and back with upholstery made of&nbsp;cold cure foam</p>
                </div>
            </div>
        </div>
{% endblock %} {% block big_products %}
        <div class="big_product_images">
            <div class="big_image">
                <img src="{% static 'img/promo-img1.jpg' %}" alt="">
                <h3 class="exclusive_text">exclusive</h3>
                <p class="big_name">Fishnet Chair</p>
                <p class="exclusive_description">Seat and back with upholstery made of&nbsp;cold cure foam. Steel frame, available in&nbsp;matt</p>
                <a href="{% url 'main:index' %}" class="buy_bottom">ORDER US <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
            </div>
            <div class="big_image">
                <img src="{% static 'img/promo-img.jpg' %}" alt="">
                <h3 class="exclusive_text">exclusive</h3>
                <p class="big_name">Fishnet Chair</p>
                <p class="exclusive_description">Seat and back with upholstery made of&nbsp;cold cure foam. Steel frame, available in&nbsp;matt</p>
                <a href="{% url 'main:index' %}" class="buy_bottom">ORDER US <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
            </div>
        </div>
{% endblock %} {% block trending_menu %}
        <div class="underslide_space">
            <ul class="featured_new_menu">
                <li><a class="trading_products" href="#">New products</a></li>
            </ul>
            <a href="{% url 'main:index' %}" class="explore_all">EXPLORE ALL <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
        </div>
{% endblock %}

        <div class="product_images padding_side">
{% block trending_products %}
            <div class="product_images padding_side">
{% for item in products %}
{% if item.isNew %}
                <div class="product_m">
                    <img src="{{ item.image.url }}" alt="{{ item.alt }}">
                    <div class="product-m-info">
                        <a class="round_button_m" href="{% url 'basket:add' item.pk %}">&gt;</a>
                        <br><br>
                        <h3>{{ item.name }}</h3>
                        <p><br><br><br>{{ item.description }}</p>
                    </div>
                </div>
{% endif %}
{% endfor %}
            </div>
            {% endblock %}
        </div>


{% block hot_deal_slider %}
        <div class="slider2">
            <div class="wrapper_hot">
                    <input type="radio" name="point_hot" id="slide1_hot" checked>
                    <input type="radio" name="point_hot" id="slide2_hot">
                    <input type="radio" name="point_hot" id="slide3_hot">
                    <input type="radio" name="point_hot" id="slide4_hot">
                    <input type="radio" name="point_hot" id="slide5_hot">
                    <div class="slider">
{% for item in products %}
{% if item.isHot %}
                        <div class="slides_hot slide{{item.SlideHotNo}}_hot">
                            <img src="/media/{{item.imageHot}}" style="margin: auto" alt="Very good product" class="sliding_image">
                            <div class="text" style="margin-left:98px">
                                <h3 style="color: #e53935">Hot deal! Only {{item.price}}$ today!</h3>
                                <h2>{{item.name}}</h2>
                                <p style="">{{item.description}}</p>
                                <a href="#" class="buy">ORDER US <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
                            </div>
                            </div>
{% endif %}
{% endfor %}
                    </div>
                    <div class="controls">
                        <label for="slide1_hot"></label>
                        <label for="slide2_hot"></label>
                        <label for="slide3_hot"></label>
                        <label for="slide4_hot"></label>
                        <label for="slide5_hot"></label>
                    </div>
                </div>

        </div>
{% endblock %}
        <!-- КОНЕЦ СЛАЙДЕРА -->
{% block exclusive %}
        <div class="padding_side underslide_space">
            <div class="big_left_product">
                <img src="{% static 'img/product-1-lg.jpg' %}" alt="">
                <h3 class="exclusive_text">exclusive</h3>
                <p class="big_name">Fishnet Chair</p>
                <p class="exclusive_description">Seat and back with upholstery made of&nbsp;cold cure foam. Steel frame, available in&nbsp;matt</p>
                <a href="{% url 'main:index' %}" class="buy_bottom">ORDER US <img style="height: 14px; width: 16px; margin-bottom: 3px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
            </div>
            <div class="small_right_products">
                <a href="#"><img class="product-sm" src="{% static 'img/product-2-sm.jpg' %}" alt=""></a>
                <a href="#"><img class="product-sm" src="{% static 'img/product-3-sm.jpg' %}" alt=""></a>
                <a href="#"><img class="product-sm" src="{% static 'img/product-4-sm.jpg' %}" alt=""></a>
                <a href="#"><img class="product-sm" src="{% static 'img/product-5-sm.jpg' %}" alt=""></a>
            </div>
        </div>
{% endblock %} {% block find_follow_favorite %}
        <div class="page_bottom">
            <div class="underslide_space_ft padding_side">
                <div class="text">
                    <h3 style="color:#6c6c6c">MOBILE APP</h3>
                    <h2 style="margin-left: 8px" class="footer_h2">FIND. FOLLOW. FAVORITE.
                    </h2>
                    <h4>Share your favorites and share your style.</h4>
                </div>
                <a class="appstore" href="#"><img  src="{% static 'img/appstore.jpg' %}" alt="AppStore"></a>
                <a class="googleplay" href="#"><img  src="{% static 'img/googleplay.jpg' %}" alt="Google Play"></a>
            </div>
        </div>
{% endblock %}
        <div class="bottom_container">
            <div class="padding_side">
                <div class="bottom_texts">
                    <div class="mini_header1">
                        <p>CONTACT US</p>
                        <p class="contacts">
                            132A Bridge Road Richmond VIC Australia
                        </p>
                        <p class="contacts">
                            Talk to&nbsp;us on&nbsp;1300&nbsp;132 info@interior.com
                        </p>
                    </div>
                    <div class="mini_header2">
                        <p>USEFUL INFORMATION</p>
                        <div class="useful_container">
                            <div class="useful1">
                                <p class="useful_info">
                                    <a href="#">SALES TERMS</a> <br> <a href="#">CUSTOMER CARE</a> <br> <a href="#">DELIVERY</a>
                                </p>
                            </div>
                            <div class="useful2">
                                <p style="margin-left: 110px;" class="useful_info">
                                    <a href="#">ARCHITECTS ACCOUNTS</a> <br> <a href="#">CAREERS</a> <br> <a href="#">ENCHANGES &amp;&nbsp;RETURNS</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="mini_header3">
                        <p>LET&rsquo;S STAY IN&nbsp;TOUCH!</p>
                        <p class="stay_touch_text">
                            Subscribe to&nbsp;know about our latest news, products and special offers just for subscribers. </p>
                        <br>
                        <div class="feedback">
                            <input type="text">
                            <form action="{% url 'main:index' %}">
                                <button class="telegram_button" type="submit"></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">

            <p style="text-align: center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, itaque nemo eveniet nam rerum reiciendis, quisquam dolores provident totam sed.</p>

        </div>
{% block time %} {{ date_text }} {{ datetime }}{% endblock %}
    </div>
</body>

mainapp/templates/products.html
{% extends "base.html" %} {% load static %} {% block title %} Interior. Products. {% endblock %}

<body>
{% block menu_and_logo_products %}
<div class="padding_side_top">
        {% include "inc/menu_top.html" %}
</div>
{% endblock %}


 <!-- {{ data.posts.0.title }} - json пример вывода -->
 {% block products_menu %}
        {% include "inc/categories_menu.html" %}
        {% endblock %} {% block div_details %}

        <!-- ПРОДУКТЫ ПО КАТЕГОРИЯМ -->
            <h2 style="text-align:center">{{ category.name|title }}</h2>
            <div class="product_images padding_side">
                {% for product in products %}
                <div class="product_m" style="line-height: 16px">
                    <img src="{{ product.image.url }}" alt="{{ product.description }}">
                    <div class="product-m-info" >
                        <a class="round_button_m" href="{% url 'basket:add' product.pk %}">&gt;</a>
                        <h3>{{ product.name }}</h3>
                        <p>Usual price is {{ product.price }} $</p>
                        <p> But now is discount time! Only {{ product.discount }} $</p>
                        <p><br><br>{{ product.description }}</p>
                        <p>На складе: {{ product.quantity }}</p>
                        <p>pk is {{ pk }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>

            {% block hot_deal %}

            <div class="details-products">
                <div class="details-slider">
                    <div class="slider-product">
                        <img src="{{ hot_product.image.url }}">
                    </div>
                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
                        </div>
                    </div>
                </div>
                {% if hot_product.pk %} <!-- РАЗОБРАТЬСЯ В КАКИХ СЛУЧАЯХ HOT_PRODUCT ПОЛУЧАЕТ PK, А В КАКИХ = НЕТ !-->
                <div class="description">
                    <h3 class="big-bold">{{ hot_product.name }}</h3>
                    <h3 class="red">Hot deal!</h3>
                    <p class="price"> {{ hot_product.price }} <span>$</span></p>
                    <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						order us <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
                    <div class="description-text">
                        <p>{{ hot_product.description }}</p>
                {% endif %}  <!-- РАЗОБРАТЬСЯ В КАКИХ СЛУЧАЯХ HOT_PRODUCT ПОЛУЧАЕТ PK, А В КАКИХ = НЕТ !-->
                    </div>
                </div>


            </div>
            {% endblock %} {% block trending_menu %}
            <div class="underslide_space">
                <ul class="featured_new_menu">
                    <li><a class="trading_products" href="#">New products</a></li>
                </ul>
                <a href="/index/" class="explore_all">EXPLORE ALL <img style="height: 13px; width: 16px" src="{% static 'img/Right_arrow_buy.png' %}" alt=""></a>
            </div>

            <div class="product_images padding_side">


                <!-- БЛОК NEW PRODUCTS -->
{% for item in new_products %}
                <div class="product_m">
                    <img src="{{ item.image.url }}" alt="{{ item.alt }}">
                    <div class="product-m-info">
                        <a class="round_button_m" href="#">&gt;</a>
                        <br><br>
                        <h3>{{ item.name }}</h3>

                        <p>{{ item.price }} $</p>
                        <p>{{ item.discount }} $</p>
                        <p>{{ item.description }}</p>
                    </div>
                </div>
 {% endfor %}
                <!-- БЛОК NEW PRODUCTS -->
            </div>
            {% endblock %}
            <div class="product_images padding_side">
            </div>{% endblock %}