MartynovStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
import debug_toolbar
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main_view),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('standartadmin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admins')),
    path('order/', include('ordersapp.urls', namespace='ordersapp')),
    path('auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    path('auth/verify/vk/oauth2/', include('social_django.urls', namespace='social')),

]
if settings.DEBUG:
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authapp/urls.py
from django.conf.urls import url
from django.urls import re_path, path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp' # название для приложения mainapp

# ссылки, которые относятся к mainapp

urlpatterns = [
    path('contact/', mainapp.contact_view, name='contact'),
    path('products/', mainapp.products_view, name='products'),
    path('index/', mainapp.main_view, name='index'),
    path('products/<int:pk>/', mainapp.products_view, name='category')
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name = "ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),

    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

ordersapp/models.py
from django.db import models

# Create your models here.


# 1 модель  - OrderItem - 1) какой продукт купили и 2) его количество
# 2 модель - Order. Она состоит из OrderItem"ов

# related_name используется для более удобной связи таблиц order_item.order - это заказ, в который входит order_item
# order_item.objects.filter(order=order) - это будет фильтрация order_item"ов по определенному заказу. Список покупок
# одного заказа ПРОЩЕ: order.RELATED_NAME.all()


from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):

    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
                'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
                'total_quantity': sum(list(map(lambda x: x.quantity, items)))
                }

    #def get_total_quantity(self):
    #    items = self.orderitems.select_related()
    #    return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    #def get_total_cost(self):
    #    items = self.orderitems.select_related()
    #    return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity -= object.quantity
            object.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    objects = OrderItemQuerySet.as_manager()

    def get_product_cost(self):
        return self.product.price * self.quantity


    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    price = forms.CharField(label='цена', required=False)

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.get_items()

ordersapp/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.views.generic.list import BaseListView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.models import Order, OrderItem

from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.views.generic.detail import DetailView
from django.urls import reverse, reverse_lazy
from django.db import transaction

from ordersapp.forms import OrderItemForm
from django.forms import inlineformset_factory

from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        # пришел гет запрос
        print('kwargs', kwargs)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        # возвращает словарь с данными
        context = super().get_context_data(*args, **kwargs)
        context['page_title'] = 'Список заказов'
        return context

    # def get_template_names(self):
    #     # возвращает шаблон который мы редактируем
    #     if self.request.user.is_staff:
    #         return 'staff.html'
    #     else:
    #         return 'other.html'

    # Изменяем свойства класса
    # 1. имя шаблона
    template_name = 'order_list.html'
    # 2. название списка в шаблоне
    # context_object_name = 'orders'

    # Изменяем методы класса
    # ------------- Основные методы -----------------
    """

    dispatch()
    # итоговый список
    get_queryset()
    get_context_data()
    get()

    """
    # ------------- Другие методы -------------------
    """
    get_template_names()
    setup()
    http_method_not_allowed()
    get_context_object_name()
    render_to_response()
    """


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')
    template_name = 'order_form.html'

    """
    Основные методы
    post() # пришел post запрос
    form_valid() # после валидации формы
    form_invalid() # если форма не валидна
    """

    def get_context_data(self, **kwargs):

        """
        Передача данных в шаблон
        :param kwargs:
        :return:
        """
        # Получаем словарь по умолчанию
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        # Создаем нужный набор форм
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=2)

        if self.request.POST:
            # сохранение данных
            # заполняем данными набор форм
            formset = OrderFormSet(self.request.POST)
        else:
            # если выводим форму
            # получаем данные из корзины
            basket_items = Basket.get_items(self.request.user)
            # если они есть
            if len(basket_items):
                # создаем набор форм длиной как в корзине
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                # создаем его экземпляр
                formset = OrderFormSet()
                # сохраняем данные корзины
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):

        """форма валидна"""
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            # сохраняем заказ
            self.object = form.save()
            if orderitems.is_valid():
                # добавляем к items заказ
                orderitems.instance = self.object
                # сохраняем сразу все
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order
    template_name = 'order_detail.html'

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context

    # get_queryset - ???

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    # Основной метод это
    # def get_object(self, queryset=None):
    #     """
    #     Возвращает нужный нам объект
    #     :param queryset:
    #     :return:
    #     """
    #     return 'Мой объект'


class OrderItemsUpdate(UpdateView):
    template_name = 'order_form.html'
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    template_name = 'order_confirm_delete.html'
    success_url = reverse_lazy('order:orders_list')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price':0})

ordersapp/templates/order_confirm_delete.html
{% extends 'orderbase.html' %}
{% load staticfiles %}

{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

ordersapp/templates/order_detail.html
{% extends 'orderbase.html' %}
{% load static %}

{% block content %}
    {% include 'includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img src="{{ item.product.image.url }}" alt="{{ item.product.short_desc }}">
                <div style="margin: 20px;" class="category_name">{{ item.product.category.name }}</div>
                <div style="margin: 20px;" class="product_name">{{ item.product.name }}</div>
                <div style="margin: 20px;" class="product_price">{{ item.product.price }}&nbspруб</div>
                <div style="margin: 20px;" class="product_quantitiy">x {{ item.quantity }} шт.</div>
                <div style="margin: 20px;" class="product_cost"> = {{ item.get_product_cost }}&nbspруб</div>
            </div>
        {% endfor %}
    </div>
    {% include 'includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/order_form.html
{% extends 'orderbase.html' %}
{% load static %}
{% load cache %}

{% block content %}
    {% include 'includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
{{ field }}
{% else %}
{% if field.value %}
<span class="orderitems-{{forloop.parentloop.counter0}}-price">
{{ field.value }}
</span> руб
{% endif %}
{% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
            {% include 'includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

ordersapp/templates/order_list.html
{% extends 'orderbase.html' %}
{% load static %}
<!-- НАЗВАНИЕ ШАБЛОНА СТРОИТСЯ КАК "НАЗВАНИЕМОДЕЛИ_LIST -->

{% block content %}
    <div class="h2 text-center head">
        Ваши заказы, {% if user.first_name %}{{ user.first_name|title}}{% else %}Пользователь{% endif %}
    </div>
    <table class="table orders_list">
        <thead>
          <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'order:order_read' item.pk %}">посмотреть</a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'order:order_update' item.pk %}">редактировать</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'order:order_delete' item.pk %}">удалить</a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main:index' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'order:order_create' %}">
            новый
        </a>
    </button>
{% endblock %}

ordersapp/templates/orderbase.html
<!-- МИНИМАЛЬНАЯ БАЗОВАЯ СОСТАВЛЯЮЩАЯ КАЖДОЙ СТРАНИЦЫ -->
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %} {% endblock %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static '/js/jquery.formset.js' %}"></script>
    <script src="{% static '/js/order_scripts.js' %}"></script>

   <!-- <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" >  -->
</head>
<body>

    <div class="container">
	<div class="order_container">
        {% block content %}
        {% endblock %}

	</div>
        <div class="clr"></div>

        <div class="bottom_container">
            <div class="padding_side">
                <div class="bottom_texts">

                    <div class="mini_header1">
                        <p>CONTACT US</p>
                        <p class="contacts">
                            132A Bridge Road Richmond VIC Australia
                        </p>
                        <p class="contacts">
                            Talk to&nbsp;us on&nbsp;1300&nbsp;132 info@interior.com
                        </p>
                    </div>
                    <div class="mini_header2">
                        <p>USEFUL INFORMATION</p>
                        <div class="useful_container">
                            <div class="useful1">
                                <p class="useful_info">
                                    <a href="#">SALES TERMS</a> <br> <a href="#">CUSTOMER CARE</a> <br> <a href="#">DELIVERY</a>
                                </p>
                            </div>
                            <div class="useful2">
                                <p style="margin-left: 110px;" class="useful_info">
                                    <a href="#">ARCHITECTS ACCOUNTS</a> <br> <a href="#">CAREERS</a> <br> <a href="#">ENCHANGES &amp;&nbsp;RETURNS</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="mini_header3">
                        <p>LET&rsquo;S STAY IN&nbsp;TOUCH!</p>
                        <p class="stay_touch_text">
                            Subscribe to&nbsp;know about our latest news, products and special offers just for subscribers. </p>
                        <br>
                        <div class="feedback">
                            <input type="text">
                            <form action="/index/">
                                <button class="telegram_button" type="submit"></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p style="text-align: center">
                {% block time %} {{ date_text }} {{ datetime }} {% endblock %}</p>
        </div>
    </div>
</body>

</html>